### PR TITLE
Getting rid of feature-variables in ModelContext

### PR DESCRIPTION
**Pull request by marcromeyn**
### Goals :soccer:
Now that we introduced the `FeatureContext` to distribute the raw-features to all blocks that want these, we don’t need the old structure anymore where we were using variables in the `ModelContext`.

### Implementation Details :construction:
This PR gets rid of all traces of the feature-variables in `ModelContext`.

### CODE REVIEW

**Comment by marcromeyn** [comment]
rerun tests

**Review by karlhigley — APPROVED** [review]

**Comment by marcromeyn** [comment]
rerun tests

**Comment by marcromeyn** [comment]
rerun tests

**Comment by marcromeyn** [comment]
rerun tests

**Pull request merged**
