### PR TITLE
Allow custom input block for two tower and fix [Bug] InputBlockV2 without schema 

### PR DESCRIPTION
**Pull request by timmy00**
Fixes # (issue)
#641 

### Goals :soccer:
Fix InputBlockV2 without schema #641 

### Implementation Details :construction:
1. Change the schema setting in ParallelBlock, in previous development, only if all sub blocks have schema, the ParallelBlock (parent of sub blocks) would be set schema. I changed it to that if any sub block has schema,  the ParallelBlock (parent of sub blocks) would be set to the collection of sub-blocks' schemas.
2. InputBlockV2 dose not have schema. Thus adding set_schema for InputBlockV2
3. Allow flexibility for TwoTower API, allow users create custom input block as item/query tower input block

### Testing Details :mag:
Test custom input block (InputBlockV2) in two-tower model

### CODE REVIEW

**Comment by gabrielspmoreira** [comment]
@timmy00  This PR is related to these issues
https://github.com/NVIDIA-Merlin/Merlin/issues/479
https://github.com/NVIDIA-Merlin/models/issues/604

**Comment by gabrielspmoreira** [comment]
rerun tests

**Review by gabrielspmoreira — APPROVED** [review]
This PR looks good to me!

**Review by marcromeyn — COMMENTED** [review]
Let’s hold off this one, seems like we should first look into the root-cause of the bug a bit more.

**Comment by timmy00** [comment]
Fixed by #649 .

**Pull request closed without merging**
