### PR TITLE
Fix prediction task documentation

### PR DESCRIPTION
**Pull request by benfred**
We've moved losses and metrics from the prediction task to model.compile in #431. However,
the docstrings for our prediction tasks still referred to these parameters, even though this
doesn't work and throws errors like:

```python
  File "/home/ben/code/models/merlin/models/tf/models/retrieval.py", line 77, in MatrixFactorizationModel
    prediction_tasks = ItemRetrievalTask(
  File "/home/ben/code/models/merlin/models/tf/prediction_tasks/retrieval.py", line 90, in __init__
    super().__init__(
  File "/home/ben/code/models/merlin/models/tf/prediction_tasks/classification.py", line 205, in __init__
    super().__init__(
  File "/home/ben/code/models/merlin/models/tf/prediction_tasks/base.py", line 70, in __init__
    super().__init__(name=name, **kwargs)
  File "/home/ben/miniconda3/envs/nvtabular/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 629, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/ben/miniconda3/envs/nvtabular/lib/python3.9/site-packages/keras/engine/base_layer.py", line 341, in __init__
    generic_utils.validate_kwargs(kwargs, allowed_kwargs)
  File "/home/ben/miniconda3/envs/nvtabular/lib/python3.9/site-packages/keras/utils/generic_utils.py", line 1174, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'loss')
```

### CODE REVIEW

**Comment by benfred** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by rnyak** [comment]
rerun tests

**Review by gabrielspmoreira — APPROVED** [review]

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Pull request merged**
