### PR TITLE
fix make file to run unit tests

### PR DESCRIPTION
**Pull request by jperez999**

### CODE REVIEW

**Review by karlhigley — APPROVED** [review]

**Comment by marcromeyn** [comment]
I am a bit confused about the need of this PR. I was under the impression that: `"tensorflow and not (integration or example)”` would take care of ignoring the integration-tests? We automatically mark the integration tests as `integration` using pytest-markers [here](https://github.com/NVIDIA-Merlin/models/blob/main/tests/conftest.py#L85-L86). Is this not working?

**Comment by karlhigley** [comment]
Yeah, the integration tests were running on all PRs for a bit. Not sure if that's still the case though.

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by oliverholworthy** [comment]
Looks like the markers are not correctly configured for the integration tests.

I've created a change here to simplify the marker creation and fix the integration test marking. #510

**Comment by benfred** [comment]
@jperez999 I don't think this is necessary after @oliverholworthy's fix in #510

**Pull request closed without merging**
