### PR TITLE
Rename UniformNegativeSampling class

### PR DESCRIPTION
**Pull request by rnyak**
Addresses https://github.com/NVIDIA-Merlin/models/issues/650

### CODE REVIEW

**Comment by oliverholworthy** [comment]
@rnyak After discussion with @marcromeyn . Seems like adding something about 'in batch' to the name may help make the name closer to it's natural sense.  Something like `InBatchNegatives` or `InBatchNegativeSampling`.

**Comment by rnyak** [comment]
> @rnyak After discussion with @marcromeyn . Seems like adding something about 'in batch' to the name may help make the name closer to it's natural sense. Something like `InBatchNegatives` or `InBatchNegativeSampling`.

Wonder if this would lead confusion for users. Since we also have in batch negative sampling in retrieval,  we dont want people to think that they can use `InBatchNegativeSampling`  class for retrieval models as well..  bcs they wont be able to, if I am not mistaken. so did we decide if InBatchNegativeSampling is only for ranking? If yes, we would explicit explanations in the docstrings to avoid confusion.

**Comment by sararb** [comment]
> > @rnyak After discussion with @marcromeyn . Seems like adding something about 'in batch' to the name may help make the name closer to it's natural sense. Something like `InBatchNegatives` or `InBatchNegativeSampling`.
> 
> @marcromeyn and @oliverholworthy Wonder if this would lead confusion for users. Since we also have in batch negative sampling in retrieval, we dont want people to think that they can use `InBatchNegativeSampling` class for retrieval models as well.. bcs they wont be able to, if I am not mistaken. so did we decide if InBatchNegativeSampling is only for ranking? If yes, we would explicit explanations in the docstrings to avoid confusion.

How about renaming the `UniformNegativeSampling` class to `SampleFromBatch`?

**Comment by oliverholworthy** [comment]
Closing this since the rename has been made in #710 to `InBatchNegatives`

**Pull request closed without merging**
