### PR TITLE
Make use of model_test for all ranking- and benchmark-models

### PR DESCRIPTION
**Pull request by marcromeyn**
### Goals :soccer:
Use the newly introduced `model_test` in all ranking- and benchmark-tests in order to ensure our models can be fitted, saved to disk & retrained.

### Implementation Details :construction:
This PR contains some bug-fixes in order to make sure models like DCN can be saved & restored.

### CODE REVIEW

**Comment by jperez999** [comment]
rerun tests

**Comment by marcromeyn** [comment]
rerun tests

**Review by gabrielspmoreira — APPROVED** [review]
The PR is ok to me @marcromeyn .
I just noticed that we are removing the calls to `testing_utils.assert_binary_classification_loss_metrics()` and to `testing_utils.assert_regression_loss_metrics()`. Are we giving up to test the loss and metrics outputs by the models?

**Comment by marcromeyn** [comment]
rerun tests

**Comment by marcromeyn** [comment]
rerun tests

**Pull request merged**
