### PR TITLE
Fix to pass shuffle argument to dataloader

### PR DESCRIPTION
**Pull request by benfred**
The 'shuffle' argument wasn't being passed to the dataloader in _maybe_convert_merlin_dataset,
and was instead just silently being ignored. This meant that it wasn't possible to
set 'shuffle=False' . Fix this, and also change the behaviour for evaluate/predict to
not shuffle the dataset - since it shouldn't ever be necessary, and in the case of predict
could return confusing results

### CODE REVIEW

**Comment by marcromeyn** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Review by oliverholworthy — APPROVED** [review]

**Pull request merged**
