### PR TITLE
Add CategoryEncoding transformation block

### PR DESCRIPTION
**Pull request by timmy00**
### Goals :soccer:
This layer provides options for condensing data into a categorical encoding. It accepts categorical features (integer values)  as inputs, and it outputs a dense or sparse representation of those inputs. The output mode can be set as one_hot, multi_hot and weighted count, inputs can be ragged tensor, sparse tensor or tensor.

### Implementation Details :construction:
similar with https://keras.io/api/layers/preprocessing_layers/categorical/category_encoding/

### Testing Details :mag:
WIP

### CODE REVIEW

**Comment by gabrielspmoreira** [comment]
This PR sounds good to me @timmy00 . What is missing here for being ready for review?

**Comment by timmy00** [comment]
> 



> This PR sounds good to me @timmy00 . What is missing here for being ready for review?

Hi @gabrielspmoreira , thank you for your review, I want to add more unit tests, including different tensors (ragged tensor, sparse tensor, dense tensor) and tensors with different dimensions (2-D tensor, 3-D tensor), in order to indicate what inputs are acceptable and what are not.

**Review by gabrielspmoreira — COMMENTED** [review]
This PR introduces `CategoryEncoding`, which in theory can be used to replace `CategoricalOneHot` for being more flexible.
After #638 is merged, test `CategoryEncoding` and compare with `CategoricalOneHot` for `WideAndDeepModel`

**Review by gabrielspmoreira — APPROVED** [review]
I have improved CategoryEncoding by checking and reshaping input 1D/2D tensors (with an approach which works with graph mode), depending on the output_mode (e.g. "one_hot" expects 1D tensors and "multi_hot"/"count" 2D tensors).
Also improved and added new tests to CategoryEncoding.

I replace in this PR the `CategoricalOneHot` references by `CategoryEncoding`, as the latter is more comprehensive to support sparse input and output, and also supports not only "one_hot", but also "multi_hot" and "count".

**Comment by gabrielspmoreira** [comment]
rerun tests

**Comment by gabrielspmoreira** [comment]
rerun tests

**Pull request merged**
