### PR TITLE
enhance pretrained-embeddings example to set trainable=False for  the pre-trained embeddings

### PR DESCRIPTION
**Pull request by rnyak**
This PR enhances the existing [entertainment-with-pretrained-embeddings.ipynb](https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/entertainment-with-pretrained-embeddings.ipynb) notebook in the following ways:
- users now can set the trainable param in the Embeddings function
-  users can use InputBlockV2 and feed to the model

### CODE REVIEW

**Review by radekosmulski — DISMISSED** [review]

**Review by radekosmulski — APPROVED** [review]

**Comment by radekosmulski** [comment]
rerun tests

**Comment by bschifferer** [comment]
Should the unittest include testing that the embedding weights did not change?

**Review by bschifferer — APPROVED** [review]
We might want to add a unittest to check, if the weights were freezed (comparing the embeddings after training with the original numpy array)

**Comment by rnyak** [comment]
> We might want to add a unittest to check, if the weights were freezed (comparing the embeddings after training with the original numpy array)

we do have a unit test [here](https://github.com/NVIDIA-Merlin/models/blob/main/tests/unit/tf/inputs/test_embedding.py#L219) if that' what you meant.

**Comment by rnyak** [comment]
rerun tests

**Comment by rnyak** [comment]
rerun tests

**Pull request merged**
