### PR TITLE
Stop reordering columns in merlin.models.xgb.dataset_to_xy

### PR DESCRIPTION
**Pull request by radekosmulski**
Fix issue where TIS is returning incorrect predictions due to data passed in incorrect order

### CODE REVIEW

**Review by karlhigley — APPROVED** [review]

**Comment by karlhigley** [comment]
rerun tests

**Comment by radekosmulski** [comment]
rerun tests

**Comment by radekosmulski** [comment]
rerun tests

**Comment by radekosmulski** [comment]
thank you very much for the review @karlhigley! was able to merge it now that the CI is up and running 🙂

**Pull request merged**
