### PR TITLE
Improvements in Wide and Deep architecture and example test based on the paper

### PR DESCRIPTION
**Pull request by timmy00**
Fixes # (issue)
https://github.com/NVIDIA-Merlin/models/pull/623#pullrequestreview-1065967254

### Goals :soccer:
- Add an example (test) of Wide and Deep architecture which is equivalent to the one proposed in [paper](https://arxiv.org/abs/1606.07792), including multiple optimizers ([FTRL](https://github.com/tensorflow/estimator/blob/eb9d58bf952fbeb9fd4e686b7528d6adf0021320/tensorflow_estimator/python/estimator/canned/optimizers.py#L104) for wide part and AdaGrad for deep part) and 2nd-level feature interactions in the wide part.
- Changed docstrings of WideAndDeepModel() to provide more examples of configurations
- Change default value of output_mode for `HashedCross` and `HashedCrossAll` from 'int' to 'one_hot', and makes them accept now 2D features (for feature interaction with `multi_hot` features)
- Provide an option for `HashedCrossAll` to ignore meaningfuless feature combinations (that always lead to the same values), for example: `[["item_id", "item_category"], ["user_id", "user_birth_city"]]`
- Replaces the `CategoricalOneHot` by `CategoryEncoding` transformation, as it supports multi-hot and sparse input/output
- Added support of multi-hot categ features into HashedCross, fixed bugs on graph mode and updated tests

Making either wide or deep part optional for wide&deep

### Implementation Details :construction:
- Use multi optimzier and model.find_blocks_by_name()
- It is important to enable the output of one-hot representations of high-cardinality features to be sparse tensors `e.g. CategoryEncoding(..., sparse=True), HashedCrossAll(..., sparse=True), HashedCross(..., sparse=True)`, otherwise memory consumption is two high and leads to OOM errors.

### Testing Details :mag:
Model test with two mode (run_eagerly = True / False)

### CODE REVIEW

**Comment by timmy00** [comment]
A weird error occured in Jenkins, it seems that HashedCross(output_mode="one_hot"), the error message is "Determinism is not yet supported in GPU implementation of DenseBincount." But in NGC, the same code could run succesfully in GPU.

**Comment by gabrielspmoreira** [comment]
rerun tests

**Comment by gabrielspmoreira** [comment]
This PR originated from a conversation with @timmy00 where I found some issues and provided her some suggestions regarding the `WideAndDeepModel`.
I have added to his PR some improvements to `WideAndDeepModel` so that it matches the original paper and provide additional options by using `HashedCrossAll`, `CategoricalOneHot`, and `ConcatFeatures`. Also improved the documention and tests.
@marcromeyn @oliverholworthy would you like to take a look before we merge?

**Review by gabrielspmoreira — APPROVED** [review]

**Comment by gabrielspmoreira** [comment]
rerun tests

**Comment by gabrielspmoreira** [comment]
rerun tests

**Comment by gabrielspmoreira** [comment]
I have added to this PR a number of fixes, improvements and tests to `HashedCross`, `HashedCrossAll` and `WideAndDeepModel` and edited the PR description to describe the main ones.

**Pull request merged**
